import type { Rule } from 'eslint';
import type { Linter } from 'eslint';
import perfectionist from 'eslint-plugin-perfectionist';
import prettier from 'eslint-plugin-prettier';
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

import noInlineTypeImports from './rules/no-inline-type-imports.js';
import multilineTypeLiterals from './rules/multiline-type-literals.js';
import moduleMemberOrder from './rules/module-member-order.js';

export const rules: Record<string, Rule.RuleModule> = {
    'no-inline-type-imports': noInlineTypeImports,
    'multiline-type-literals': multilineTypeLiterals,
    'module-member-order': moduleMemberOrder,
};

const projectAliasPattern =
    '^@(assets(?:/illustrations)?|shared|adapters|features|infrastructure|components|services|configs|domain|utils|hooks)(?:/.*)?$';

export const configs: {
    recommended: Linter.Config;
    react: Linter.Config[];
} = {
    recommended: {
        plugins: {
            nava: { rules },
        },
        rules: {
            'nava/no-inline-type-imports': 'error',
            'nava/multiline-type-literals': 'error',
            'nava/module-member-order': 'error',
            '@typescript-eslint/consistent-type-imports': [
                'error',
                { prefer: 'type-imports', fixStyle: 'separate-type-imports' },
            ],
        },
    },

    react: [
        js.configs.recommended,
        ...tseslint.configs.recommended,
        {
            plugins: {
                nava: { rules },
                perfectionist,
                prettier,
            },
            rules: {
                ...perfectionist.configs['recommended-line-length'].rules,
                'prettier/prettier': 'error',
                'nava/no-inline-type-imports': 'error',
                'nava/multiline-type-literals': 'error',
                'nava/module-member-order': 'error',
                '@typescript-eslint/consistent-type-imports': [
                    'error',
                    { prefer: 'type-imports', fixStyle: 'separate-type-imports' },
                ],
                'perfectionist/sort-imports': [
                    'error',
                    {
                        groups: [['builtin', 'external'], ['alias'], ['parent', 'sibling', 'index'], 'unknown'],
                        customGroups: [
                            { elementNamePattern: projectAliasPattern, groupName: 'alias' },
                            { elementNamePattern: '^src/', groupName: 'sibling' },
                        ],
                        fallbackSort: { type: 'alphabetical', order: 'asc' },
                        type: 'line-length',
                        newlinesBetween: 1,
                        order: 'desc',
                    },
                ],
                '@typescript-eslint/explicit-function-return-type': 'off',
                'no-empty': ['error', { allowEmptyCatch: true }],
                'perfectionist/sort-modules': 'off',
                'react/react-in-jsx-scope': 'off',
                'react/prop-types': 'off',
            },
            languageOptions: {
                parser: tseslint.parser,
                parserOptions: {
                    ecmaFeatures: { jsx: true },
                    ecmaVersion: 'latest',
                    sourceType: 'module',
                },
                globals: {
                    AbortController: 'readonly',
                    URLSearchParams: 'readonly',
                    sessionStorage: 'readonly',
                    clearInterval: 'readonly',
                    clearTimeout: 'readonly',
                    localStorage: 'readonly',
                    setInterval: 'readonly',
                    setTimeout: 'readonly',
                    navigator: 'readonly',
                    document: 'readonly',
                    console: 'readonly',
                    window: 'readonly',
                    fetch: 'readonly',
                    URL: 'readonly',
                },
            },
            settings: { react: { version: 'detect' } },
        },
    ],
};

export default { rules, configs };

// generated by build
